export const PageName = {
    ROOT: 'Root',
    LOADING: 'Loading',
    TAB_NAVIGATOR: 'TabNavigator',
    LOGIN: 'Login',
    LOGOUT: 'Logout',
    REGISTER: 'Register',
    ACTIVATE_ACCOUNT_PAGE: 'ActivateAccountPage',
    HOME: 'Home',
    CHAT: 'Chat',
    CHAT_DETAIL: 'ChatDetail',
    CHAT_PERSONAL: 'ChatPersonal',
    PROFILE: 'Profile',
    EDIT_PROFILE: 'Chỉnh sửa trang cá nhân',
    LIST_FRIENDS: 'Danh sách bạn bè',
    EDIT_USER: 'Chỉnh sửa thông tin cá nhân',
    CREATE_POST_PAGE: 'CreatePostPage',
    POST_DETAIL_PAGE: 'PostDetailPage',
    FRIEND_PROFILE: 'Trang cá nhân bạn bè',
};
